discardDataFromIO: discardDataFromIO.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror -std=c++20 -o discardDataFromIO.exe discardDataFromIO.cpp

cinCheckState: cinCheckState.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror -std=c++20 -o cinCheckState.exe cinCheckState.cpp

cinWhileCheckState: cinWhileCheckState.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror -std=c++20 -o cinWhileCheckState.exe cinWhileCheckState.cpp

cinMemberFunc: cinMemberFunc.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror -std=c++20 -o cinMemberFunc.exe cinMemberFunc.cpp