calculateTip: calculateTip.cpp
	g++ -g -ggdb -Wall -Wextra -o calculateTip.exe calculateTip.cpp

swapToX: swapToX.cpp
	g++ -g -ggdb -pedantic -Wall -Wextra -Werror -o swapToX.exe swapToX.cpp

CircleCalc: CircleCalc.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o CircleCalc.exe CircleCalc.cpp