calculateTip: calculateTip.cpp
	g++ -g -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o calculateTip.exe calculateTip.cpp

swapToX: swapToX.cpp
	g++ -g -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o swapToX.exe swapToX.cpp

CircleCalc: CircleCalc.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o CircleCalc.exe CircleCalc.cpp

divByZero: divByZero.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o divByZero.exe divByZero.cpp